# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go API

env:
  BASE_URL: 'https://sutin1234.github.io/react-ts-go'
  API_FREFIX: 'api'
  API_VERSION: 'v1'
  PORT: 8000

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.0'

    - name: Install dependencies
      run: cd go-server && go version && go get -u golang.org/x/lint/golint

    - name: Build Golang
      run: cd go-server && ls -la && go build -o bin/main
      env:
        BASE_URL: ${{env.BASE_URL}}
        API_FREFIX: ${{env.API_FREFIX}}
        API_VERSION: ${{env.API_VERSION}}
        PORT: ${{env.PORT}}

#    - name: Linting Go
#      run: cd go-server && golint .

    - name: Test Golang
      run: cd go-server && go test -v ./...

    - name: Run Golang
      run: ./go-server/bin/main
